apiVersion: v1
kind: Secret
metadata:
  name: github-actions-secret
  namespace: hdk-web
  annotations:
    kubernetes.io/service-account.name: github-actions
type: kubernetes.io/service-account-token